### ISSUE TITLE
Dark mode for sites (especially the Document and REPL)

### ISSUE THREAD

**Issue by NewUserHa** [sveltejs/sites#266] opened 2022-01-09 15:18 UTC
dark mode is good for eyes, and good for the new developers that prepare to start svelte.

svelte is a front-end thing and should not be late on dark mode. And the dark theme should looks nice for the same reason.

so the dark theme should learn from those well designed products theme like vscode dark, youtube dark, windows dark.

related: https://github.com/sveltejs/sites/issues/147 https://github.com/sveltejs/sites/issues/97 https://github.com/sveltejs/sites/issues/105

**Comment by dummdidumm** [comment] 2022-01-09 16:13
Duplicate of #147 and #97 . Please comment on the existing issues instead.

**Closed by dummdidumm** 2022-01-09 16:13 UTC
