### ISSUE TITLE
link to API from the tutorial

### ISSUE THREAD

**Issue by weepy** [sveltejs/sites#47] opened 2021-06-28 14:16 UTC
Hi - I'm not sure where the best place to suggest this idea is, but it would be really helpful to link to the API docs from the tutorial. Often I will find myself in the tutorial looking at a feature (probably from a google search), but I need a deeper explanation within the API.

**Comment by Conduitry** [comment] 2021-06-28 17:47
Duplicate of https://github.com/sveltejs/svelte/issues/4955

**Closed by Conduitry** 2021-06-28 17:47 UTC
