### ISSUE TITLE
Deleted REPL apps do not get removed from list until hard refresh

### ISSUE THREAD

**Issue by MattheousDT** [sveltejs/sites#459] opened 2023-04-07 22:18 UTC
### Describe the bug

When deleting an item from the "My Apps" view on the REPL, deleting an app doesn't change the list on the client-side but manually refreshing does confirm that the item has been deleted.

### Reproduction

https://user-images.githubusercontent.com/28923903/230685496-ac93b644-04d1-45fc-91e8-b3b5d1eff15b.mp4

### System Info

```shell
N/A
Windows 10, Firefox 111.0.1
```

### Severity

annoyance

**Comment by Conduitry** [comment] 2023-04-07 23:57
I just transferred this to the appropriate repo - but it looks like this is actually a duplicate of #443. Closing.

**Closed by Conduitry** 2023-04-07 23:57 UTC
