### ISSUE TITLE
REPLs not sorted if only saved once

### ISSUE THREAD

**Issue by Florian-Schoenherr** [sveltejs/sites#191] opened 2021-12-16 19:06 UTC
I just opened a REPL, added some stuff, logged in, saved and didn't find the newly saved REPL at the top of the list.
I opened a new REPL and pasted the code there again, saved again, still didn't find at the top and then guessed it might be further down, where I then found it.

looks like this, which is about 10 REPLs down the list:
![image](https://user-images.githubusercontent.com/65456722/146432773-73c2983f-e52f-4f9d-8a59-22d1dc17d690.png)
"23min ago" are the new ones, maybe sorting isn't invoked? my only guess.

**Comment by Rich-Harris** [comment] 2021-12-17 02:29
Can you check if this is still happening? I have a feeling it may have been fixed by some recent changes, and I can't reproduce it. Thanks

**Comment by Florian-Schoenherr** [comment] 2021-12-17 09:09
still happening:
![image](https://user-images.githubusercontent.com/65456722/146518654-f9fa094c-ece4-44c7-95ee-dda7fb1ad504.png)
also tried removing cache

**Comment by oskarhane** [comment] 2021-12-17 10:37
Looks like the `updated_at` for gists defaults to `null` and the sorting for the listing is `.order('updated_at', { ascending: false })`.

```js
[
  {
    id: 'eebd9abe99ed43d2b8e76148ab3b5bbb',
    name: 'x1',
    created_at: '2021-12-17T10:19:17.194688+00:00',
    updated_at: '2021-12-17T10:25:36.629409+00:00'
  },
  {
    id: 'cd1478907c9c44a0acaabc04ab90e2b6',
    name: 'fork1',
    created_at: '2021-12-17T10:25:53.917134+00:00',
    updated_at: null
  },
  {
    id: '57414d5885c6485684a1272a3fb4676e',
    name: 'fork2',
    created_at: '2021-12-17T10:25:57.424429+00:00',
    updated_at: null
  }
]
```

Not sure how you do db migrations, but for the `setup.sql` I'd set 

```pgsql
create table public.gist (
	id uuid default extensions.uuid_generate_v4() not null primary key,
	created_at timestamptz default now(),
	name text,
	files json,
	updated_at timestamptz default now(), /* added default to now() */
	userid int8
);
```

**Comment by Florian-Schoenherr** [comment] 2021-12-17 12:02
@oskarhane that's it!
If I update one of the REPLs and save it again, it appears at the top.

**Comment by oskarhane** [comment] 2021-12-17 13:27
Actually, the above suggestion might not be ideal.

I'd probably go for editing the `public.gist_create` pg function instead.

Something like

```pgsql
create or replace function public.gist_create (name text, files json, userid int8)
returns record
language plpgsql volatile
as $$
	declare
		ret record;
	begin
		insert into gist (name, files, userid, updated_at) /* insert updated_at */
		values (name, files, userid, now()) returning gist.id, gist.name, gist.files, gist.userid into ret;

		return ret;
	end;
$$;

```

Let me know if this makes sense @Rich-Harris and I'll open a PR if you want.
Again not sure how you handle migrations on the existing db.

**Comment by Rich-Harris** [comment] 2021-12-17 16:30
Ah yep, this makes sense. Hmm. I think there's some value in keeping `updated_at` as `null` for gists that haven't been updated, which makes me think it would be better to order by `coalesce(updated_at, created_at)` which would have the desired effect.

Unfortunately I don't _think_ you can express that with PostgREST, so we might need to use a stored function. Investigating...

**Closed** 2021-12-17 17:35 UTC
Labels: bug

**Comment by Rich-Harris** [comment] 2021-12-17 17:48
should be fixed now, please reopen if not!

**Comment by Florian-Schoenherr** [comment] 2021-12-17 18:51
thank you, works :)
