### ISSUE TITLE
@sveltejs/svelte-repl || workersUrl required

### ISSUE THREAD

**Issue by yoh-extradat** [sveltejs/sites#377] opened 2022-09-02 12:20 UTC
Example from src/routes/index throws error:

```
You must supply workersUrl prop to <Repl>
Error: You must supply workersUrl prop to <Repl>
    at eval (/node_modules/@sveltejs/svelte-repl/src/Repl.svelte:97:9)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at eval (/src/routes/test/+page.svelte:43:133)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.default (root.svelte:41:38)
    at eval (/src/routes/+layout.svelte:10:32)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at root.svelte:40:37
    at $$render (/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.render (/node_modules/svelte/internal/index.mjs:1778:26)
```

Not sure how to provide a proper workersUrl. Any help would be much appreciated!

**Comment by benmccann** [comment] 2024-11-12 22:11
closing as duplicate of https://github.com/sveltejs/svelte.dev/issues/838

**Closed by benmccann** 2024-11-12 22:11 UTC
