### ISSUE TITLE
https://svelte.dev/tutorial/basics and https://svelte.dev/examples broken on Safari 14.0.3

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/sites#91] opened 2021-04-26 13:35 UTC
Browser: Safari 14.0.3
OS: macOS 11.2.3

After emptying my browse cache, when I navigate to https://svelte.dev/tutorial/basics, seeing...

- loading editor... below upper rectangle on right
- loading Svelte compiler... below lower rectangle on right.
- \n\n\t\n\t\t\n\n\t\t\n\t\n\t\n appears in the Result in the lower right rectangle
- JavaScript console has these errors:

> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/global.css.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (global.css, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/prism.css.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (prism.css, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/svelte-logo-horizontal.svg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-logo-horizontal.svg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/icons/edit.svg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (edit.svg, line 0)
> [Error] SyntaxError: Invalid escape in identifier: '\'
> 	(anonymous function) (about:srcdoc:1)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/client/client.d22d392f.js.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (client.d22d392f.js, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/fonts/overpass/overpass-latin-600.woff2.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (overpass-latin-600.woff2, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/fonts/overpass/overpass-latin-300.woff2.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (overpass-latin-300.woff2, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/fonts/fira-mono/fira-mono-latin-400.woff2.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (fira-mono-latin-400.woff2, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/favicon.png.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (favicon.png, line 0)

When navigating to https://svelte.dev/examples, similar issue but many more JavaScript console errors...

> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/global.css.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (global.css, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/prism.css.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (prism.css, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/hello-world.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (hello-world.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/dynamic-attributes.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (dynamic-attributes.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/styling.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (styling.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/nested-components.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (nested-components.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/html-tags.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (html-tags.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/reactive-assignments.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (reactive-assignments.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/reactive-declarations.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (reactive-declarations.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/reactive-statements.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (reactive-statements.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/declaring-props.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (declaring-props.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/default-values.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (default-values.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/spread-props.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (spread-props.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/if-blocks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (if-blocks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/else-blocks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (else-blocks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/else-if-blocks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (else-if-blocks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/each-blocks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (each-blocks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/keyed-each-blocks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (keyed-each-blocks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/await-blocks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (await-blocks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/dom-events.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (dom-events.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/inline-handlers.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (inline-handlers.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/event-modifiers.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (event-modifiers.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/component-events.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (component-events.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/event-forwarding.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (event-forwarding.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/dom-event-forwarding.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (dom-event-forwarding.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/text-inputs.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (text-inputs.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/numeric-inputs.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (numeric-inputs.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/checkbox-inputs.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (checkbox-inputs.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/group-inputs.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (group-inputs.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/textarea-inputs.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (textarea-inputs.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/file-inputs.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (file-inputs.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/select-bindings.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (select-bindings.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/multiple-select-bindings.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (multiple-select-bindings.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/each-block-bindings.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (each-block-bindings.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/media-elements.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (media-elements.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/dimensions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (dimensions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/bind-this.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (bind-this.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/component-bindings.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (component-bindings.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/onmount.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (onmount.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/ondestroy.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (ondestroy.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/update.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (update.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/tick.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (tick.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/writable-stores.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (writable-stores.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/auto-subscriptions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (auto-subscriptions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/readable-stores.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (readable-stores.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/derived-stores.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (derived-stores.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/custom-stores.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (custom-stores.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/tweened.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (tweened.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/spring.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (spring.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/transition.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (transition.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/adding-parameters-to-transitions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (adding-parameters-to-transitions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/in-and-out.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (in-and-out.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/custom-css-transitions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (custom-css-transitions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/custom-js-transitions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (custom-js-transitions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/transition-events.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (transition-events.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/deferred-transitions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (deferred-transitions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/animate.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (animate.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/easing.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (easing.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/clock.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (clock.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/bar-chart.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (bar-chart.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/area-chart.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (area-chart.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/scatterplot.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (scatterplot.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svg-transitions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svg-transitions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/actions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (actions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/adding-parameters-to-actions.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (adding-parameters-to-actions.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/classes.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (classes.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/class-shorthand.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (class-shorthand.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/slots.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (slots.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/slot-fallbacks.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (slot-fallbacks.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/named-slots.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (named-slots.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/slot-props.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (slot-props.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/conditional-slots.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (conditional-slots.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/modal.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (modal.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/context-api.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (context-api.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svelte-self.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-self.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svelte-component.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-component.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/svelte-logo-horizontal.svg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-logo-horizontal.svg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svelte-window.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-window.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svelte-window-bindings.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-window-bindings.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svelte-body.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-body.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/svelte-head.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (svelte-head.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/module-exports.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (module-exports.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/debug.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (debug.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/7guis-counter.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (7guis-counter.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/7guis-temperature.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (7guis-temperature.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/7guis-flight-booker.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (7guis-flight-booker.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/7guis-timer.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (7guis-timer.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/7guis-crud.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (7guis-crud.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/7guis-circles.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (7guis-circles.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/hacker-news.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (hacker-news.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/examples/thumbnails/immutable-data.jpg.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (immutable-data.jpg, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/client/client.d22d392f.js.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (client.d22d392f.js, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/fonts/overpass/overpass-latin-600.woff2.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (overpass-latin-600.woff2, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/fonts/overpass/overpass-latin-300.woff2.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (overpass-latin-300.woff2, line 0)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/fonts/fira-mono/fira-mono-latin-400.woff2.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (fira-mono-latin-400.woff2, line 0)
> [Error] SyntaxError: Invalid escape in identifier: '\'
> 	(anonymous function) (about:srcdoc:1)
> [Error] FetchEvent.respondWith received an error: Returned response is null.
> [Error] Cannot load https://svelte.dev/favicon.png.
> [Error] Failed to load resource: FetchEvent.respondWith received an error: Returned response is null. (favicon.png, line 0)

When I use Google Chrome 90 on the same MacBook, no errors. Everything works as expected.

**Comment by Rich-Harris** [comment] 2021-12-21 02:26
Is this still happening?

**Comment by benmccann** [comment] 2024-11-12 22:41
closing since no one has confirmed this still happening and the site has been rewritten

**Closed by benmccann** 2024-11-12 22:41 UTC
Labels: bug, browser support
