### ISSUE TITLE
Sitemap.xml

### ISSUE THREAD

**Issue by nosovk** [sveltejs/sites#18] opened 2021-04-13 19:33 UTC
It would be nice to generate\update sitemap.xml with links to all content.

**Comment by benmccann** [comment] 2021-04-23 20:05
What would be the point of this? There's only four pages on the site, so a web crawler will easily discover everything

**Comment by nosovk** [comment] 2021-04-23 20:52
people use this repo as an example, small howto. In common people need to generate sitemaps, it's better to leave an example.

**Comment by benmccann** [comment] 2021-04-23 21:21
Closing as duplicate of https://github.com/sveltejs/kit/issues/1142

**Closed by benmccann** 2021-04-23 21:21 UTC
