### ISSUE TITLE
Duplication of REPL on save

### ISSUE THREAD

**Issue by shahul01** [sveltejs/sites#204] opened 2021-12-19 19:25 UTC
Bug maybe is due to new REPL
![image](https://user-images.githubusercontent.com/53307156/146688003-93f41e69-7f9a-48e8-9a4d-02167b3a3cb3.png)

I have pressed Save so many times
And each save is saved separately as REPL

And a way to delete the old REPL would be nice too

**Comment by oskarhane** [comment] 2021-12-20 21:42
Yeah, this happens to me too from time to time since a week back or so. 
I'll have a look at it if I get time in the coming days.

**Comment by Rich-Harris** [comment] 2021-12-21 01:27
I'm unable to reproduce this, is it still happening?

**Comment by oskarhane** [comment] 2021-12-21 08:25
Yes, this happens more frequently (but not exclusively) in Safari.

Typical scenarios (but not consistent behavior):

---

1. Load a saved gist
2. Click save
3. See duplicates in https://svelte.dev/repl/apps

---

1. Load a saved gist
2. Fork it
3. Click save one or multiple times
4. See duplicates in https://svelte.dev/repl/apps

**Comment by shahul01** [comment] 2021-12-21 10:16
So I logged out and logged in to see if the error persisits on creating and saving a new REPL, after saving it, I tried to go  to apps and got 500 error

![image](https://user-images.githubusercontent.com/53307156/146912861-b15e5575-2830-480f-a507-1ac0a3a7c263.png)

**Comment by ignatiusmb** [comment] 2021-12-21 10:18
500 error is unrelated and would be fixed by #234

**Comment by shahul01** [comment] 2021-12-21 14:34
It still gives 500 error
![image](https://user-images.githubusercontent.com/53307156/146946789-1fd5a4fc-8251-4ec7-9af6-dfd89a43f191.png)


I went to [svelte.dev/apps](https://svelte.dev/apps), it showed my apps with delete option(Thank you for making that btw). But after saving a REPL to test duplication, it gave 500 error...

**Comment by shahul01** [comment] 2022-01-07 04:00
I logged out and relogged in, doesn't give error to me for now but don't know if its due to any other update or just relogging.

**Comment by AlbertMarashi** [comment] 2022-04-28 14:50
This is happening for everyone in my team

**Comment by benmccann** [comment] 2024-11-12 22:38
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists

**Closed by benmccann** 2024-11-12 22:38 UTC
